# Generated by Django 3.0.5 on 2020-07-05 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='fitst_name',
            new_name='first_name',
        ),
    ]
