# Generated by Django 3.0.5 on 2020-07-05 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dateadvert',
            options={'ordering': ['-id'], 'verbose_name': 'Срок', 'verbose_name_plural': 'Сроки'},
        ),
    ]
