# Generated by Django 3.0.5 on 2020-07-14 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callboard', '0002_auto_20200705_0328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advert',
            old_name='discription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='advert',
            old_name='prise',
            new_name='price',
        ),
    ]
